apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-app
  template:
    metadata:
      labels:
        app: azure-app
    spec:
      containers:
      - name: azure-app
        image: {{  .Values.imageRepo}}/azure-app:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
