# Pipeline definition that runs CI automatically for the master branch.
pr: none
trigger:
  branches:
    include:
      - master

variables:
  - group: az-app-variables

pool:
  vmImage: ubuntu-latest

stages:
  - stage: "Build_Push_Azure_App_Image"
    displayName: "Build and Push Azure App Image"
    jobs:
      - job: "Build_Push_App_Image"
        displayName: "Build Push App Image"
        steps:
          - template: build-container-template.yaml
            parameters:
            sourceLocation: /azure-app
            dockerFile: "Dockerfile"
            acr: $(AZ_ACR_NAME)
            repository: azapp/azure-app-front
            taskname: "HelloWorld_image"

            

  
      
