trigger: none

resources:
  pipelines:
    - pipeline: az-app-ci
      source: "arc-gitops-demo-src CI"
      trigger:
        branches:
          include:
            - master
  repositories:
    - repository: Manifest
      type: git
      name: arc-gitops-demo-env
 
name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  - group: az-app-variables
  - name: images_artifact_path
    value: $(Pipeline.Workspace)/az-vote-ci/image_tags
  - name: manifests_artifact_path
    value: $(Pipeline.Workspace)/az-vote-ci/manifests
  - name: utils_artifact_path
    value: $(Pipeline.Workspace)/az-vote-ci/utils

pool:
  vmImage: ubuntu-latest
  
stages:
  - stage: "deploy_app"
    displayName: "Deploy to app"
    jobs:
      - deployment: Deploy_to_app
        displayName: "Deploy to app"
        environment: app
        strategy:
          runOnce:
            deploy:
              steps:
                - template: deployment-template.yaml
                
                
                
                
                
